package com.sap.unal.webservice.repositories;

import com.sap.unal.webservice.entities.Maestro;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface MaestroRepository extends JpaRepository<Maestro, Long> {
    @Query(value = "select 'BOG' ENC_PREFIJO, Pago.nroRecibo ENC_NRORECIB, '1001' ENC_SEDE, substring(Pago.fecha,0,4) ENC_VIGENCIA, '2014' ENC_NITEMES, 'BOGOTÁ' ENC_NOMBRESEDE, 'SERVICIO DE ATENCIÓN PSICOLÓGICA' ENC_EMPRESAQUIPU, Pago.fecha ENC_FECEMIC, '1' ENC_TIPODOC, '1' ENC_FORMAPAGO, '' ENC_FECPAGO, if(chkBanco = 4,'Sin Recibo',if(chkBanco = 3,'Caja',if(chkBanco = 2,'PSE',if(chkBanco = 1,'Banco',if(chkBanco = 0,'Datafono',''))))) ENC_MEDIOPAGO, '0' ENC_DESCUENTO, Pago.valorPagado ENC_SUBTOTAL, Pago.valorPagado ENC_TOTAL, '' ENC_OBSERVACIONES, '' ENC_DATOS_PAGO, '11001' ENC_CIUDAD_SEDE, 'Av. Diagonal 40 A bis No. 15-38' ENC_DIR_SEDE, '3165000 ext 29207' ENC_TELEF_SEDE, 'sap_fchbog@unal.edu.co' ENC_EMAIL_SEDE_EMISION, '1' ENC_CLINATU, concat(consultante.nombres,' ',consultante.apellidos) ENC_CLINOMB, consultante.tipoDocumento ENC_CLI_TIPOID, consultante.nit ENC_CLI_NUMID, consultante.idMunicipioResidencia ENC_CLICIUDAD, consultante.direccion ENC_CLIDIR, consultante.telefono ENC_CLITELEF, consultante.email ENC_CLIEMAIL, '' ENC_CLIRESPFIS, '' ENC_CLIRESPIVA, '' ENC_DOCU_HIJO, '1' ENC_COD_PRESTADOR, consultante.tipoDocumento ENC_TIPODOC_USUARIO, consultante.nit\t ENC_NUM_IDENTIFICACION, upper(trim(substring_index(consultante.apellidos, ' ', 1))) ENC_PRIMER_APELLIDO, upper(trim(replace(consultante.apellidos, substring_index(consultante.apellidos, ' ', 1), ''))) ENC_SEGUNDO_APELLIDO, upper(trim(substring_index(consultante.nombres, ' ', 1))) ENC_PRIMER_NOMBRE, upper(trim(replace(consultante.nombres, substring_index(consultante.nombres, ' ', 1), ''))) ENC_SEGUNDO_NOMBRE, '8' ENC_TIPO_USUARIO, '12' ENC_MODALIDAD_CONTRATO, '15' ENC_COBERTURA, '' ENC_NUM_AUTORIZACION, '' ENC_NUM_MIPRES, '' ENC_NUM_ENTREGA_MIPRES, '' ENC_NUM_CONTRATO, '' ENC_POLIZA, '' ENC_COPAGO, '' ENC_CUOTA_MODERADORA, '' ENC_CUOTA_RECUPERACION, '' ENC_PAGOS_COMPARTIDOS from Pago left join Cita on Cita.idPago=Pago.id left join InformeResumen on InformeResumen.idPago=Pago.id left join Caso on Caso.id=Cita.idCaso or InformeResumen.idCaso=Caso.id left join TallerInscritos on Pago.id=TallerInscritos.idPago left join Taller on TallerInscritos.idTaller=Taller.id left join Person terapeuta on  Cita.idTerapeuta=terapeuta.id or Taller.idTallerista1=terapeuta.id left join Person consultante on Pago.idPerson=consultante.id left join Procedimiento on Cita.idProcedimiento=Procedimiento.id or Procedimiento.id=InformeResumen.idProcedimiento or Procedimiento.id=Taller.idProcedimiento left join Proceso on Procedimiento.idProceso=Proceso.id where Pago.fechaRegistro = ?1 and Pago.idOrdenPago is null group by Pago.id;", nativeQuery = true)
    List<Maestro> findMaestro(String date);
}
